### ISSUE TITLE
Hi This is working great.

### ISSUE THREAD

**Issue by karthikkavin** [choopage/angular2-rc4-auth-routing#2]
I have some confusion, when we load a component as default and it will have left side list of customer items. In right side page have some details like customer. When we click left side list item it will pass parameter and also change route to refresh the detail component.

Can you please explain this how to setup routing?

**Comment by jek-bao-choo** [comment]
Hi @Karthik

I'm not sure if I uds your question. I'm assuming you're interested to know more abt Component Communication.

If I'm right, have you checked out this? https://angular.io/docs/ts/latest/cookbook/component-communication.html

This guide provides various a holistic explanation of comp comm.

**Comment by karthikkavin** [comment]
Thanks!

**Comment by karthikkavin** [comment]
Hi @choopage 
   http://localhost:4200/employeedetail/23.
   This is my browser url, I am using angular 2 routing, How to hide the id 23 or like any sensitive data in browser Url? Is this possible?

**Comment by jek-bao-choo** [comment]
Hi @karthikkavin it seems to me your question is How to do routing without using Route Parameters or Query Parameters?

I haven't tried this scenario. I'm not sure how it should be done exactly. Think on my feet, have you tried passing the param as Local Variables between components? 

Frankly speaking, I prefer a site with proper Route Parameters to hiding it. I find it hard to share specific post/article/task (whatever the site is meant to be) with my peers. Will you mind sharing what you're thinking with hiding the Route Parameters or Query Parameters?

**Comment by karthikkavin** [comment]
I think Query Parameters to hide from url address bar.

**Comment by jek-bao-choo** [comment]
Hi @karthikkavin my apology for my tardy response. I don't have an exact solution to recommend. Maybe try extending from this idea https://www.reddit.com/r/Angular2/comments/4u2bnt/handling_multiple_views_without_routing/

**Comment by jek-bao-choo** [comment]
hi @karthikkavin  I may not be able to answer all your question. This book by Victor Savkin looks good and should be able to answer your questions. https://leanpub.com/router

**Comment by karthikkavin** [comment]
@choopage Thank for your replay. I will checked.
